In [1]:
import numpy as np
import tensorflow as tf

## tf.Tensor vs np.array

Tensors are a type of array used by Tensorflow. They have a lot in common with numpy arrays.

In [2]:
arr = np.array([[1, 2, 5], [5,7,3]])

In [3]:
arr

array([[1, 2, 5],
       [5, 7, 3]])

Convert a numpy array to a Tensorflow tensor with the following line:

In [4]:
tensor = tf.convert_to_tensor(arr)

2021-09-30 00:21:06.795375: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [8]:
tensor

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 5],
       [5, 7, 3]])>

In [11]:
tensor.shape

TensorShape([2, 3])

In [12]:
tensor.dtype

tf.int64

In [13]:
tensor.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 5],
       [5, 7, 3]])>>

Access the numpy array by using `.numpy()`

In [14]:
tensor.numpy()

array([[1, 2, 5],
       [5, 7, 3]])

Tensors and array share some attributes, such as shape.

In [15]:
arr.shape

(2, 3)

In [16]:
tensor.shape

TensorShape([2, 3])

## Operations on tensors

Similarly to np.arrays, we can perform operation on tensors.

In [17]:
tensor

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 5],
       [5, 7, 3]])>

Element-wise multiplication

In [18]:
tensor * 2

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 2,  4, 10],
       [10, 14,  6]])>

Broadcasting rules apply.

In [22]:
tf.constant([1, 2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [23]:
tensor * tf.constant([3, 2, 2], dtype=tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 3,  4, 10],
       [15, 14,  6]])>

## Additional attribute & methods

Find the tensor location

In [24]:
tensor.device

'/job:localhost/replica:0/task:0/device:CPU:0'

Move tensor to the gpu by calling `tensor.gpu()`

In [25]:
tensor.gpu()

Instructions for updating:
Use tf.identity instead.


RuntimeError: GPU:0 unknown device.

In [29]:
tensor.cpu()

Instructions for updating:
Use tf.identity instead.


<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 5],
       [5, 7, 3]])>