In [1]:
import tensorflow as tf

### Variables

Variables are tensors with fixed type and shape but their values can be changed through operations.

In [2]:
x = tf.constant([[1.0, 2.0]])

2021-10-01 17:40:18.944462: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

We can create a variable from a tensor by calling `tf.Variable`

In [4]:
x_var = tf.Variable(x)

tf.Variable share attributes with tensors

In [5]:
x_var

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

In [6]:
x_var.shape

TensorShape([1, 2])

In [7]:
x_var.numpy()

array([[1., 2.]], dtype=float32)

In [8]:
x1 = tf.Variable([[1.0, 2.0]])
x1

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

### Gradient

`tf.Variable` allow us to calculate gradients

In [9]:
x = tf.Variable([[1.0, 2.0]])

We use the `tf.GradientTape` api to calculate the gradient of a function

In [13]:
with tf.GradientTape() as tape:
    y = x**2
    
    dy_dx = tape.gradient(y, x)

In [16]:
with tf.GradientTape() as tape:
    y = x**2
    
dy_dx = tape.gradient(y, x)

In [17]:
dy_dx

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2., 4.]], dtype=float32)>

In [18]:
dy_dx.numpy()

array([[2., 4.]], dtype=float32)