In [1]:
import numpy as np

In [7]:
g = np.array([0, 0, 100, 100])
g

array([  0,   0, 100, 100])

In [53]:
# p = np.array([90, 90, 200, 210])
# p = np.array([0, 0, 100, 100])
p = np.array([110, 110, 200, 200])
p

array([110, 110, 200, 200])

In [54]:
max_x = np.max([g[2], p[2]])
max_x

200

In [55]:
max_y = np.max([g[3], p[3]])
max_y

200

In [56]:
mat_g = np.zeros((max_y, max_x))
mat_g.shape

(200, 200)

In [57]:
mat_g[g[1]:g[3], g[0]:g[2]] = 1
mat_g

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [58]:
mat_p = np.zeros((max_y, max_x))
mat_p.shape

(200, 200)

In [59]:
mat_p[p[1]:p[3], p[0]:p[2]] = 1
mat_p

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [60]:
count_one_mat_g = np.sum(mat_g == 1)
count_one_mat_g

10000

In [61]:
count_one_mat_p = np.sum(mat_p == 1)
count_one_mat_p

8100

In [62]:
mat_g_intersect_mat_p = np.sum(mat_g + mat_p == 2)
mat_g_intersect_mat_p

0

In [63]:
mat_g_union_mat_p = count_one_mat_g + count_one_mat_p - mat_g_intersect_mat_p
mat_g_union_mat_p

18100

In [64]:
iou = mat_g_intersect_mat_p / mat_g_union_mat_p
iou

0.0

In [66]:
gt_classes = np.array([1, 1, 1, 1, 2, 1, 1, 1])

In [67]:
pred_classes = np.array([1, 2, 1, 2, 1])

In [69]:
ious = np.array(
 [[0.84313051, 0.         ,0.       ,  0.         ,0.23860974],
 [0.         ,0.08469791 ,0.4243356  ,0.         ,0.        ],
 [0.         ,0.         ,0.         ,0.73221757 ,0.        ],
 [0.         ,0.41277874 ,0.83450504 ,0.         ,0.        ],
 [0.         ,0.68758782 ,0.43810509 ,0.         ,0.        ],
 [0.12221933 ,0.         ,0.         ,0.         ,0.66359447],
 [0.02888778 ,0.         ,0.         ,0.         ,0.        ],
 [0.         ,0.         ,0.02499868 ,0.         ,0.        ]])

In [70]:
ious

array([[0.84313051, 0.        , 0.        , 0.        , 0.23860974],
       [0.        , 0.08469791, 0.4243356 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.73221757, 0.        ],
       [0.        , 0.41277874, 0.83450504, 0.        , 0.        ],
       [0.        , 0.68758782, 0.43810509, 0.        , 0.        ],
       [0.12221933, 0.        , 0.        , 0.        , 0.66359447],
       [0.02888778, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02499868, 0.        , 0.        ]])

In [92]:
tp = 0
fp = 0

In [93]:
for i in range(len(gt_classes)):
    for j in range(len(pred_classes)):
        if ious[i][j] > 0.5:
            if gt_classes[i] == pred_classes[j]:
                tp+=1
            else:
                fp+=1    
                
tp, fp

(4, 1)

In [94]:
fn = np.sum(np.max(ious, axis=1) <= 0.5)
fn

3

In [95]:
precision = tp / (tp + fp)
precision

0.8

In [96]:
recall = tp / (tp + fn)
recall

0.5714285714285714

In [75]:
a = 0


1

In [77]:
a+=1
a

3