# Exercise 1 

## Part 1 - Calculate IoU

### Objectives

In the first part of this exercise, your task is to implement a function that calculates the iou between
two bounding boxes. 

### Details

The `calculate_ious` function in `iou.py` takes two arrays containing the bounding boxes coordinates
as inputs. Both arrays are 1x4 numpy arrays. The array are using the following format:
```
[x1, y1, x2, y2]
```
where `x1 < x2` and `y1 < y2`. `(x, y1)` are the coordinates of the upper left corner 
and `(x2, y2)` the coordinates of the lower right corner of the bounding box.

### Example

```
iou = calculate_iou(np.array([0, 0, 100, 100]), np.array([101, 101, 200, 200]))
```

### Tips

Keep in mind that the bounding boxes may not intersect, in which case the IoU 
should be equal to 0.

By running `python iou.py`, you will be able to check your implementation. 


## Part 2 - calculate Precision / Recall

### Objectives

Then, you are asked to calculate the precision and recall for a given set of predictions 
and ground truths. You will use a threshold of 0.5 IoU to determine if a prediction is 
a true positive or not.

### Details

The `precision_recall` function in `precision_recall.py` takes as inputs a `ious` NxM array of IoU values as well as 
two list `pred_classes` and`gt_classes` containing the M predicted classes ids and the N ground truth classes ids.

The `ious` array contains the pairwise IoU values between the N ground truth bounding boxes and the M 
predicted bounding boxes such that:

```
ious[x, y] = calculate_iou(groundtruth[x], predictions[y])
```

### Example

```
precision, recall = precision_recall(np.array([[0.5, 0.1], [0.8, 0.1]), np.array([1, 2]), np.array([1, 0]))
```

### Tips

You need to calculate the number of False Negatives to calculate the recall. You can use the IoU array
to find the ground truth bounding boxes that are not predicted.

By running `python precision_recall.py`, you will be able to check your implementation.


In [1]:
import numpy as np

In [7]:
g = np.array([0, 0, 100, 100])
g

array([  0,   0, 100, 100])

In [53]:
# p = np.array([90, 90, 200, 210])
# p = np.array([0, 0, 100, 100])
p = np.array([110, 110, 200, 200])
p

array([110, 110, 200, 200])

In [54]:
max_x = np.max([g[2], p[2]])
max_x

200

In [55]:
max_y = np.max([g[3], p[3]])
max_y

200

In [56]:
mat_g = np.zeros((max_y, max_x))
mat_g.shape

(200, 200)

In [57]:
mat_g[g[1]:g[3], g[0]:g[2]] = 1
mat_g

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [58]:
mat_p = np.zeros((max_y, max_x))
mat_p.shape

(200, 200)

In [59]:
mat_p[p[1]:p[3], p[0]:p[2]] = 1
mat_p

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [60]:
count_one_mat_g = np.sum(mat_g == 1)
count_one_mat_g

10000

In [61]:
count_one_mat_p = np.sum(mat_p == 1)
count_one_mat_p

8100

In [62]:
mat_g_intersect_mat_p = np.sum(mat_g + mat_p == 2)
mat_g_intersect_mat_p

0

In [63]:
mat_g_union_mat_p = count_one_mat_g + count_one_mat_p - mat_g_intersect_mat_p
mat_g_union_mat_p

18100

In [64]:
iou = mat_g_intersect_mat_p / mat_g_union_mat_p
iou

0.0

In [66]:
gt_classes = np.array([1, 1, 1, 1, 2, 1, 1, 1])

In [67]:
pred_classes = np.array([1, 2, 1, 2, 1])

In [69]:
ious = np.array(
 [[0.84313051, 0.         ,0.       ,  0.         ,0.23860974],
 [0.         ,0.08469791 ,0.4243356  ,0.         ,0.        ],
 [0.         ,0.         ,0.         ,0.73221757 ,0.        ],
 [0.         ,0.41277874 ,0.83450504 ,0.         ,0.        ],
 [0.         ,0.68758782 ,0.43810509 ,0.         ,0.        ],
 [0.12221933 ,0.         ,0.         ,0.         ,0.66359447],
 [0.02888778 ,0.         ,0.         ,0.         ,0.        ],
 [0.         ,0.         ,0.02499868 ,0.         ,0.        ]])

In [70]:
ious

array([[0.84313051, 0.        , 0.        , 0.        , 0.23860974],
       [0.        , 0.08469791, 0.4243356 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.73221757, 0.        ],
       [0.        , 0.41277874, 0.83450504, 0.        , 0.        ],
       [0.        , 0.68758782, 0.43810509, 0.        , 0.        ],
       [0.12221933, 0.        , 0.        , 0.        , 0.66359447],
       [0.02888778, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02499868, 0.        , 0.        ]])

In [92]:
tp = 0
fp = 0

In [93]:
for i in range(len(gt_classes)):
    for j in range(len(pred_classes)):
        if ious[i][j] > 0.5:
            if gt_classes[i] == pred_classes[j]:
                tp+=1
            else:
                fp+=1    
                
tp, fp

(4, 1)

In [94]:
fn = np.sum(np.max(ious, axis=1) <= 0.5)
fn

3

In [95]:
precision = tp / (tp + fp)
precision

0.8

In [96]:
recall = tp / (tp + fn)
recall

0.5714285714285714

In [75]:
a = 0


1

In [77]:
a+=1
a

3

In [1]:
import numpy as np

from iou import calculate_ious
from utils import get_data


def precision_recall(ious, gt_classes, pred_classes):
    """
    calculate precision and recall
    args:
    - ious [array]: NxM array of ious
    - gt_classes [array]: 1xN array of ground truth classes
    - pred_classes [array]: 1xM array of pred classes
    returns:
    - precision [float]
    - recall [float]
    """

    # IMPLEMENT THIS FUNCTION
    tp = 0
    fp = 0
    for i in range(len(gt_classes)):
        for j in range(len(pred_classes)):
            if ious[i][j] > 0.5:
                if gt_classes[i] == pred_classes[j]:
                    tp+=1
                else:
                    fp+=1    

    tp, fp
    
    fn = np.sum(np.max(ious, axis=1) <= 0.5)
    fn
    
    precision = tp / (tp + fp)
    precision    
    
    recall = tp / (tp + fn)
    recall    
        
    return precision, recall


if __name__ == "__main__": 
    ground_truth, predictions = get_data()
    
    # get bboxes array
    filename = 'segment-1231623110026745648_480_000_500_000_with_camera_labels_38.png'
    gt_bboxes = [g['boxes'] for g in ground_truth if g['filename'] == filename][0]
    gt_bboxes = np.array(gt_bboxes)
    gt_classes = [g['classes'] for g in ground_truth if g['filename'] == filename][0]

    pred_bboxes = [p['boxes'] for p in predictions if p['filename'] == filename][0]
    pred_boxes = np.array(pred_bboxes)
    pred_classes = [p['classes'] for p in predictions if p['filename'] == filename][0]

    print('gt_bboxes', gt_bboxes)        
    print('gt_classes', gt_classes)  
    print('pred_boxes', pred_boxes)  
    print('pred_classes', pred_classes)
    
    ious = calculate_ious(gt_bboxes, pred_boxes)
    print('ious\n', ious)    
    
    precision, recall = precision_recall(ious, gt_classes, pred_classes)
    print('solution', precision, recall)

gt_bboxes [[ 793 1134 1001 1718]
 [ 737    0  898  260]
 [ 763  484  878  619]
 [ 734    0 1114  277]
 [ 853    0 1280  250]
 [ 820 1566  974 1914]
 [ 762  951  844 1175]
 [ 748  197  803  363]]
gt_classes [1, 1, 1, 1, 2, 1, 1, 1]
pred_boxes [[ 783 1104 1011 1700]
 [ 853    0 1220  200]
 [ 734    0 1100  240]
 [ 753  474  868  609]
 [ 830 1500 1004 1914]]
pred_classes [1, 2, 1, 2, 1]
ious
 [[0.84313051 0.         0.         0.         0.23860974]
 [0.         0.08469791 0.4243356  0.         0.        ]
 [0.         0.         0.         0.73221757 0.        ]
 [0.         0.41277874 0.83450504 0.         0.        ]
 [0.         0.68758782 0.43810509 0.         0.        ]
 [0.12221933 0.         0.         0.         0.66359447]
 [0.02888778 0.         0.         0.         0.        ]
 [0.         0.         0.02499868 0.         0.        ]]
solution 0.8 0.5714285714285714
