In [1]:
import numpy as np

from matplotlib import pyplot as plt

from scipy.stats import chi2

In [2]:
chi2.ppf(0.995, 2)

10.596634733096073

In [72]:
a_mat = np.matrix([
    [1, 2, 3],
    [4, 5, -6],
    [7, 8, np.inf]
])


# a_mat = np.ones((3,3)) * np.inf

a_mat

# - find indices of closest track and measurement for next update
# - return NAN if no more associations can be found (i.e. minimum entry in association matrix is infinity)
# - delete row and column in association matrix for closest track and measurement
# - remove found track number from unassigned_tracks, meas number from unassigned_meas
# - return indices of closest track and measurement for next update

matrix([[ 1.,  2.,  3.],
        [ 4.,  5., -6.],
        [ 7.,  8., inf]])

In [73]:
b_mat = a_mat

In [98]:
b_mat


matrix([[ 1.,  2.,  3.],
        [ 4.,  5., -6.],
        [ 7.,  8., inf]])

In [74]:
np.argmin(a_mat)

5

In [75]:
min_row, min_col = np.unravel_index(np.argmin(a_mat, axis=None), a_mat.shape)
min_row, min_col

(1, 2)

In [76]:
min_val = a_mat[min_row, min_col]
min_val

-6.0

In [77]:
if min_val == np.inf:
    print('return')
else:
    print('go')

go


In [78]:
a_mat = np.delete(a_mat, min_row, axis=0)
a_mat

matrix([[ 1.,  2.,  3.],
        [ 7.,  8., inf]])

In [79]:
a_mat = np.delete(a_mat, min_col, axis=1)
a_mat

matrix([[1., 2.],
        [7., 8.]])

In [80]:
b_mat

matrix([[ 1.,  2.,  3.],
        [ 4.,  5., -6.],
        [ 7.,  8., inf]])

In [81]:
track_list = list(range(3))
track_list

[0, 1, 2]

In [82]:
track_list = np.delete(track_list, min_row)
track_list

array([0, 2])

In [83]:
mea_list = list(range(3))
mea_list

[0, 1, 2]

In [84]:
mea_list = np.delete(mea_list, min_col)
mea_list

array([0, 1])

In [88]:
np.max([0, -0.1])

0.0

In [89]:
np.min([1, 1.2])

1.0

In [94]:
True & False

False

In [97]:
True | False

True

In [102]:
x = np.matrix([[10],
               [1],
               [-1],
               [0],
               [0],
               [0]])

In [107]:
x[0][0]

matrix([[10]])

In [108]:
x[0, 0]

10

In [ ]:
1, QA: when to decrease track score outside FOV?