In [16]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

learnrate = 0.5
x = np.array([1, 2])
y = np.array(0.5)

# Initial weights
w = np.array([0.5, -0.5])

# Calculate one gradient descent step for each weight
# TODO: Calculate output of neural network
# nn_output = None
nn_output = sigmoid( np.dot( w, x))

# TODO: Calculate error of neural network
# error = None
error = y - nn_output

# TODO: Calculate change in weights
# del_w = None
del_w = learnrate * error * sigmoid_prime(np.dot( w, x)) * x


print('Neural Network output:')
print(nn_output)
print('Amount of Error:')
print(error)
print('Change in Weights:')
print(del_w)

Neural Network output:
0.3775406687981454
Amount of Error:
0.1224593312018546
Change in Weights:
[0.0143892 0.0287784]


In [27]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
w = np.array([[1, 2], [3, 4], [5, 6]])

In [32]:
w

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.dot(w, x)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [26]:
np.dot(x.T, w)

array([-1., -1.])

In [21]:
x.T

array([1, 2])

In [38]:
x = np.array([[1, 2]])

In [39]:
x

array([[1, 2]])

In [40]:
x.T

array([[1],
       [2]])

In [37]:
x[:, None]

array([[1],
       [2]])